version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "HELLO WORLD!" > ~/output.txt

      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: alpine:latest
    steps: 
      - attach_workspace:
          at: ~/ 
      - run: cat output.txt

workflows:
  my_workflows:
    jobs:
      - save_hello_world_output
      - print_output_file:
        requires:
          -save_hello_world_output
