version: 2.1
  
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
        name: "echo an env avr that is part of our project"
        command: |
          echo $my_env_var

workflows:
  test-env-vars:
    jobs:build